# -*- coding: utf-8 -*-
"""exception.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T9uVKXv6A93GcaA3jQQ_I1NEDx8ksp9i
"""

# exception handling

try:
  x = int(input("Enter dividend: "))
  y = int(input("Enter  divisor: "))

  res = x/y
except ZeroDivisionError as e:
  print(e)
  print("A number can't be divided by zero")
except ValueError as e:
  print(e)
  print("Enter numbers only")
except Exception as e:
  print(e)
  print("Error!!!")
else:
  print(res)
finally:
  print("Exception occurs or not, this line will print anyway.....")