# -*- coding: utf-8 -*-
"""File.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uj1bF9q8-uMi90N9_UUhoINr8NsTSvjC
"""

#FILE
import os

# file detection

path = "provide a file or folder path here"

if os.path.exists(path):
  print("The path exists")
  if os.path.isfile(path):
    print("This is a file")
  elif os.path.isdir(path):
    print("This is a directory")
else:
  print("The path doesn't exists")

# read from file

try:
  with open('file name','r') as file:
    print(file.read())
except FileNotFoundError:
  print("File Not Found!!!")

# write in file

text = "This text will be written in the file\nSecond line\nThird line"
try:
  with open('file name','w') as file:
    file.write(text)
except FileNotFoundError:
  print("File Not Found!!!")

# copy file
# copyfile() -> copy the contents of a file
# copy() -> copyfile() + permission mode + destination can be a directory
# copy2() -> copy() + includes metadata 

import shutil

shutil.copy2('#src','#dest')

# move a file

source - 'source file'
destination = 'destiantion directory'

try:
  if os.path.isexists(destination):
    print("File already exists at the directory")
  else:
    os.replace(source,destination)
except FileNotFoundError as e:
  print(e)

# delete a file

path = "file name"
try:
  os.remove(path)         # delete a file
  os.rmdir(path)          # delete an empty folder/directory
  os.rmtree(path)         # delete a folder including files in it
except FileNotFoundError as e:
  print(e)
except PermissionError as e:
  print(e)
except OSError as e:
  print(e)
else:
  print("The file is deleted")