# -*- coding: utf-8 -*-
"""list tuple set dict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R_S89VevDJK3A4ld7lNiJz2kl7ZCoLJv
"""

#LIST
#LIST -> square brace, mutable/dynamic
list1 = ["burger","pizza","pasta","sandwich","salad"]
list2 = ["spoon","fork","plate","knife"]
drinks = ["cola","pepsi","juice"]

list1.append("shawarma")
list1.remove("salad")
list1.insert(2,"ice cream")
list2.sort()
list2.pop()
#list1.clear()
drinks.append("water")

for i in list1:
  print(i)

for i in list2:
  print(i)

for i in drinks:
  print(i)


# 2D List
food_table = [list1,list2,drinks]

print("I would love to have "+food_table[0][1]+" on my "+food_table[1][2])
print("I eat "+food_table[0][3]+" with "+food_table[1][0])
print(food_table[2][0]+" or "+food_table[2][2])
print("Cut the "+food_table[0][4]+" with "+food_table[1][1])

#TUPLE
#TUPLE -> round braces, immutable, ordered
tuple1 = ("spoon","fork",45.32,"plate","knife",21,37)

print(tuple1.index("plate"))
for i in tuple1:
    print(i)

#SET
#SET -> curly braces, set([]) , non repeating item, unordered, unindexed
drinks = {"cola","pepsi","fanta","sprite","pepsi"}
juice = {"mango","watermelon","orange"}
fav = {"cola","watermelon","mango"}

fav.add("water")
for i in fav:
  print(i)

print()
drinks.remove("sprite")
for i in drinks:
  print(i)

print()
print(juice.difference(fav))         # JUICE - FAV


print()
print(fav.difference(juice))         # FAV - JUICE

#drinks.union(fav)

print()
print(juice.intersection(fav))       # COMMON ELEMENTS IN JUICE & FAV

print()
drinks.update(juice)            # ADD JUICE ELEMENTS WITH DRINKS ELEMENTS
for i in drinks:
  print(i)

#DICTIONARY
#DICTIONARY -> curly braces, values are referred to a key. keys are immutable and unique

capital = {'Bangladesh' : 'Dhaka',
           'USA' : 'Washington DC',
           'Germany' : 'Berlin',
           'India' : 'Delhi',
           'China' : 'Beijing'}

capital.update({'Russia':'Moscow'})
capital.pop('India')
capital.keys()                        # ONLY PRINTS THE KEYS
capital.values()                      # ONLY PRINTS THE VALUES

# PRINT KEYS AND VALUES ALTOGETHER
for keys,values in capital.items():
  print(keys+":"+values)