# -*- coding: utf-8 -*-
"""math library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gCjBjHjtiFiVIaJfGGxxUi88QjRdym1Y
"""

import math
x=16
y=3
z=7.75
neg = -8.5
Pi = 3.1416
print(math.ceil(z))
print(math.floor(z))
print(math.fabs(neg))
print(math.pow(x,y))
print(math.sqrt(x))
print(math.factorial(5))
print(math.fmod(x,y))
print(math.gcd(x,y))
print(math.modf(z))
print(math.remainder(x,y))
print(math.log(1000))
print(math.log10(1000))
print(math.log2(256))
print(math.degrees(Pi))
print(math.radians(180))

# AVAILABLE IN PYTHON VERSION 3.7

#print(math.nextafter(x, math.inf))                             #goes up: towards positive infinity.
#print(math.nextafter(x, -math.inf))                            #goes down: towards minus infinity.
#print(math.nextafter(x, 0.0))                                  #goes towards zero.
#print(math.nextafter(x, math.copysign(math.inf, x)))           #goes away from zero

