# -*- coding: utf-8 -*-
"""MatPlotLib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16YZ9tQSaawmdfcUEHzVh1e4Qlpcw1rGS
"""

from matplotlib import pylab as plt
import numpy as np

#------------------------------------------------------------
x = np.array([0,10])
y = np.array([0,100])
plt.plot(x,y, 'r')            # THIRD PARAMETER r STANDS FOR RED COLOR
plt.show()                    # COLOR CODE ARE ALSO APPLICABLE
#------------------------------------------------------------
y = np.array([7,2,5,1,9,6])
plt.plot(y, marker='*')       # MARKER HIGHLIGHTS THE Y-POINTS
plt.show()                    # AVAILABLE MARKERS * , D(DIAMOND) X(X-SHAPE) P(PENTAGON) O(O-SHAPE)
#------------------------------------------------------------
plt.plot(y, linestyle='dotted')
plt.show()                    # AVAILABLE LINESTYLES- DOTTED, DASHED, SOLID)
#------------------------------------------------------------
# PLOT MULTIPLE LINE IN ONE GRAPH
x1 = np.array([3,7,1,4,9])
y1 = np.array([8,2,4,1,7])

x2 = np.array([1,3,8,2,6])
y2 = np.array([7,9,3,5,1])

plt.plot(x1,y1, 'r',x2,y2, 'g')
plt.show()
#------------------------------------------------------------




#------------------------------------------------------------