# -*- coding: utf-8 -*-
"""string format.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111wrJjrGGa-8GWself9Fdhp1FxQBgCZx
"""

# STRING FORMAT

animal = "cat"
item = "table"

print("The "+animal+" jumped over the "+item)                 # usual string printing method
print("The {} jumped over the {}".format("cat","table"))      # string formatting using value
print("The {} jumped over the {}".format(animal,item))        # string formatting using variable

text = "The {} jumped over the {}"
print(text.format(animal,item))                               # more time efficient for common tex

pi = 3.1416
num = 1000

print("The value of pi is {:.2f}".format(pi))                 # takes 2 digit after decimal point
print("The formatted number: {:,}".format(num))               # comma separated
print("Binary of the number: {:b}".format(num))
print("Octal of the number: {:o}".format(num))
print("Hexadecimal of the number: {:X}".format(num))
print("Scientific format of the number: {:e}".format(num))